package model

import (
	"time"

	"gorm.io/gorm"
)

// User represents a registered desktop user.
type User struct {
	ID        uint           `gorm:"primaryKey" json:"id"`
	Email     string         `gorm:"uniqueIndex;size:255;not null" json:"email"`
	Password  string         `gorm:"size:255;not null" json:"-"` // bcrypt hash
	Plan      string         `gorm:"size:16;default:free" json:"plan"` // free / pro / premium
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

// Pairing represents a desktop-mobile or desktop-desktop pairing relationship.
type Pairing struct {
	PairingID         string         `gorm:"primaryKey;size:36" json:"pairing_id"`
	DesktopUserID     uint           `gorm:"index;not null" json:"desktop_user_id"`           // server (B) user_id
	ClientUserID      uint           `gorm:"index" json:"client_user_id"`                    // desktop pair: client (A) user_id; mobile pair: 0
	InitiatorUserID   uint           `gorm:"index" json:"initiator_user_id"`                 // desktop pair: phone user who initiated; mobile pair: 0
	MobileUserID      uint           `gorm:"index" json:"mobile_user_id"`                    // mobile pair: phone user_id (from JWT at Complete); desktop pair: 0
	DesktopDeviceID   string         `gorm:"size:255" json:"desktop_device_id"`              // server (B) device ID
	DesktopName       string         `gorm:"size:255" json:"desktop_name"`                   // server (B) name
	MobileDeviceID    string         `gorm:"size:255" json:"mobile_device_id"`               // mobile pair: phone device ID; desktop pair: client (A) device ID
	MobileName        string         `gorm:"size:255" json:"mobile_name"`                    // mobile pair: phone name; desktop pair: client (A) name
	MobilePubkey      string         `gorm:"size:255" json:"mobile_pubkey"`                  // ECDH P-256 public key (hex); desktop pair: empty
	PairingType       string         `gorm:"size:16;default:mobile" json:"pairing_type"`     // mobile | desktop
	Status            string         `gorm:"size:16;default:pending" json:"status"`          // pending / pending_approval / completed / revoked
	JoinBatchID       string         `gorm:"index;size:36" json:"join_batch_id"`             //关联的 JoinBatch ID（外键 → JoinBatch.BatchID，可空，仅 desktop 互联配对有值）
	DevicePublicKey   []byte         `gorm:"type:blob" json:"device_public_key"`             //桌面端设备公钥（mobile 配对时桌面端提交，Complete 时自动注册到 DeviceKey 表）
	KeySecurityLevel  string         `gorm:"size:16" json:"key_security_level"`              //密钥存储安全等级（high/medium/low）
	TrustLevel        string         `gorm:"size:16;default:full" json:"trust_level"`        //D5: 信任级别（full=本机+互联网络 / local_only=仅本机）
	PairingKeyHex     string         `gorm:"size:64" json:"pairing_key_hex"`                 // desktop pair: 32-byte pairing key (hex), generated by phone, stored for recovery
	CreatedAt         time.Time      `json:"created_at"`
	CompletedAt       *time.Time     `json:"completed_at"`
	RevokedAt         *time.Time     `json:"revoked_at"`
}

// ConfigCiphertext stores encrypted server config for a pairing.
type ConfigCiphertext struct {
	ID         uint      `gorm:"primaryKey" json:"id"`
	PairingID  string    `gorm:"uniqueIndex;size:36;not null" json:"pairing_id"`
	Ciphertext string    `gorm:"type:text;not null" json:"ciphertext"` // base64 AES-256-GCM
	Nonce      string    `gorm:"size:64;not null" json:"nonce"`        // base64 nonce
	UpdatedAt  time.Time `json:"updated_at"`
}

// PlanLimits stores WebSocket concurrency limits per subscription plan.
type PlanLimits struct {
	Plan         string    `gorm:"primaryKey;size:16" json:"plan"` // free / pro / premium
	DesktopWSMax int       `json:"desktop_ws_max"`
	MobileWSMax  int       `json:"mobile_ws_max"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// JoinBatch stores batch-level metadata for desktop interconnection requests.
// All desktop pairing flows (initial/join/merge/repair) go through JoinBatch.
type JoinBatch struct {
	BatchID           string     `gorm:"primaryKey;size:36" json:"batch_id"`
	InitiatorUserID   uint       `gorm:"index;not null" json:"initiator_user_id"`
	DesktopAUserID    uint       `gorm:"not null" json:"desktop_a_user_id"`
	DesktopADeviceID  string     `gorm:"size:255;not null" json:"desktop_a_device_id"`
	DesktopAName      string     `gorm:"size:255" json:"desktop_a_name"`
	DesktopBUserID    uint       `gorm:"not null" json:"desktop_b_user_id"`
	DesktopBDeviceID  string     `gorm:"size:255;not null" json:"desktop_b_device_id"`
	DesktopBName      string     `gorm:"size:255" json:"desktop_b_name"`
	FlowType          string     `gorm:"size:16;not null" json:"flow_type"`           // initial / join / merge / repair
	RequiredApprovals uint       `gorm:"not null" json:"required_approvals"`
	ReceivedApprovals uint       `gorm:"default:0" json:"received_approvals"`
	Status            string     `gorm:"size:16;default:pending_approval;index:idx_join_batch_status_expires,priority:1" json:"status"` // pending_approval / approved / completed / expired
	ServerNonce       []byte     `gorm:"type:blob" json:"server_nonce"`                         // 32 bytes random nonce
	BatchContentHash  []byte     `gorm:"type:blob" json:"batch_content_hash"`                   // SHA256(canonical_json(target_members))
	CreatedAt         time.Time  `json:"created_at"`
	ExpiresAt         time.Time  `gorm:"index:idx_join_batch_status_expires,priority:2" json:"expires_at"`
}

// JoinApproval stores each individual signature approval for a JoinBatch.
type JoinApproval struct {
	ID               uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	BatchID          string    `gorm:"size:36;not null;uniqueIndex:idx_join_approval_unique" json:"batch_id"`
	ApproverUserID   uint      `gorm:"not null;uniqueIndex:idx_join_approval_unique" json:"approver_user_id"`
	ApproverDeviceID string    `gorm:"size:255;not null;uniqueIndex:idx_join_approval_unique" json:"approver_device_id"`
	Signature        []byte    `gorm:"type:blob;not null" json:"signature"`     // ECDSA P-256 DER, base64-decoded
	Payload          []byte    `gorm:"type:blob;not null" json:"payload"`       // canonical JSON that was signed
	NetworkGroup     uint      `gorm:"not null" json:"network_group"`           // from snapshot, used for cross-group validation
	CreatedAt        time.Time `json:"created_at"`
}

// JoinBatchNetworkSnapshot stores the network membership snapshot at batch creation time.
// Used for cross-NetworkGroup validation without real-time topology computation.
type JoinBatchNetworkSnapshot struct {
	ID           uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	BatchID      string    `gorm:"index;size:36;not null" json:"batch_id"`
	NetworkGroup uint      `gorm:"not null" json:"network_group"`
	UserID       uint      `gorm:"not null" json:"user_id"`
	DeviceID     string    `gorm:"size:255;not null" json:"device_id"`
	DeviceName   string    `gorm:"size:255" json:"device_name"` // display name for batch-info API
	CreatedAt    time.Time `json:"created_at"`
}

// AuditLog stores security events for incident response and compliance.
// Append-only — records are never deleted.
type AuditLog struct {
	LogID          uint      `gorm:"primaryKey;autoIncrement" json:"log_id"`
	EventType      string    `gorm:"size:32;index;not null" json:"event_type"`
	BatchID        string    `gorm:"index;size:36" json:"batch_id"`
	ActorUserID    uint      `json:"actor_user_id"`
	ActorDeviceID  string    `gorm:"size:255" json:"actor_device_id"`
	TargetUserID   uint      `json:"target_user_id"`
	TargetDeviceID string    `gorm:"size:255" json:"target_device_id"`
	Detail         string    `gorm:"type:text" json:"detail"` // JSON string
	CreatedAt      time.Time `gorm:"index" json:"created_at"`
}

// DeviceKey stores desktop device public keys for signature verification.
// Supports key rotation via active/superseded status.
// Uniqueness of active key per (user_id, device_id) is enforced at application layer
// (service checks for existing active key before insert). Superseded records have no
// unique constraint, allowing multiple historical entries for audit.
type DeviceKey struct {
	ID               uint       `gorm:"primaryKey;autoIncrement" json:"id"`
	UserID           uint       `gorm:"not null;index:idx_device_key_lookup" json:"user_id"`
	DeviceID         string     `gorm:"size:255;not null;index:idx_device_key_lookup" json:"device_id"`
	PublicKey        []byte     `gorm:"type:blob;not null" json:"public_key"` // ECDSA P-256, 65 bytes uncompressed (0x04+X+Y)
	KeySecurityLevel string     `gorm:"size:16" json:"key_security_level"`   // high / medium / low
	Status           string     `gorm:"size:16;default:active;index:idx_device_key_lookup" json:"status"` // active / superseded
	CreatedAt        time.Time  `json:"created_at"`
	SupersededAt     *time.Time `json:"superseded_at"`
}
