[package]
name = "termfast-test-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
russh = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
ssh-key = { version = "0.7.0-rc.11", features = ["rand_core", "getrandom", "encryption"] }
