// TypeScript types matching Rust structs — §4.2
// These MUST match crates/core/src/config/config.rs exactly.

// === Server types ===

export type ServerStatus =
  | "connected"
  | "connecting"
  | "reconnecting"
  | "auth_failed"
  | "disconnected"
  | "offline";

/// SSH connection configuration (matches Rust SshConfig)
export interface SshConfig {
  host: string;
  port: number;
  user: string;
  /// "key" | "password"
  auth_method: string;
  /// Path to private key file (for key auth)
  key_path: string;
  /// Whether the key was auto-generated by TermFast
  key_auto_generated: boolean;
  /// "single" | "dual"
  connection_mode: string;
  /// Skip hostkey verification (security downgrade)
  skip_hostkey_verify: boolean;
}

/// Proxy configuration (matches Rust ProxyConfig)
export interface ProxyConfig {
  enabled: boolean;
  socks5_port: number;
  http_port: number;
  /// Mixed port (0 = disabled). When non-zero, both SOCKS5 and HTTP share this port.
  mixed_port: number;
  /// Max concurrent SSH channels for proxy
  max_channels: number;
  /// Idle timeout for proxy channels in seconds
  channel_idle_timeout: number;
}

/// Reconnection configuration (matches Rust ReconnectConfig)
export interface ReconnectConfig {
  auto_reconnect: boolean;
  heartbeat_interval: number;
  max_attempts: number;
  initial_backoff_secs: number;
  max_backoff_secs: number;
}

/// IP check configuration (matches Rust IpCheckConfig)
export interface IpCheckConfig {
  enabled: boolean;
  interval_secs: number;
}

/// Trigger instance (matches Rust TriggerInstance)
export interface TriggerInstance {
  id: string;
  template_id: string;
  trigger_type: TriggerType;
  name: string;
  enabled: boolean;
  continue_on_error: boolean;
  timeout_secs: number;
  notify_on_success: boolean;
  notify_on_failure: boolean;
  parameters: Record<string, string>;
  commands: string[];
  template_hash_at_addition: string;
  cooldown_secs: number;
  last_fired_at: string | null;
}

/// Server configuration (matches Rust ServerConfig)
export interface ServerConfig {
  id: string;
  name: string;
  ssh: SshConfig;
  proxy: ProxyConfig;
  reconnect: ReconnectConfig;
  ip_check: IpCheckConfig;
  last_known_ip: string | null;
  triggers: TriggerInstance[];
  suppress_firewall_badge: boolean;
}

// === SECTION 1 END ===

// === Template types ===

/// Trigger type (matches Rust TriggerType enum)
export type TriggerType =
  | "OnConnect"
  | "OnReconnect"
  | "OnIpChange"
  | "OnProcessDead"
  | "OnPortClosed"
  | "ManualFire";

/// Parameter schema (matches Rust ParameterSchema)
export interface ParameterSchema {
  name: string;
  label: string;
  /// "port" | "string" | "token" | "number"
  param_type: string;
  required: boolean;
  default: string;
  validation: string;
}

/// Trigger template (matches Rust TriggerTemplate)
export interface TriggerTemplate {
  id: string;
  name: string;
  /// serde rename = "type"
  type: TriggerType;
  description: string;
  built_in: boolean;
  template_version: number;
  parameters_schema: ParameterSchema[];
  commands: string[];
  /// For on_process_dead: process name to check
  check_target: string;
  /// For on_process_dead / on_port_closed: check interval in seconds
  check_interval: number;
  /// Default timeout for commands
  timeout_secs: number;
}

// === Config types ===

/// General config (matches Rust GeneralConfig)
export interface GeneralConfig {
  auto_start: boolean;
  minimize_to_tray: boolean;
  /// "system" | "light" | "dark"
  theme: string;
  /// "system" | "zh-CN" | "en"
  language: string;
  /// "trace" | "debug" | "info" | "warn" | "error"
  log_level: string;
  max_log_entries: number;
  log_to_file: boolean;
  log_dir: string;
  log_max_days: number;
  log_max_size_mb: number;
  /// Which server's proxy is set as system proxy (null = none)
  system_proxy_server_id: string | null;
  /// URL for proxy connectivity test
  proxy_test_url: string;
  crash_reporting: boolean;
  suppress_firewall_badge: boolean;
  // Proxy defaults
  default_socks5_port: number;
  default_http_port: number;
  default_queue_timeout_secs: number;
  // Trigger defaults
  default_trigger_timeout_secs: number;
  default_continue_on_error: boolean;
  default_ip_check_interval_secs: number;
  // Notification preferences
  notify_connect_success: boolean;
  notify_disconnect: boolean;
  notify_reconnect_success: boolean;
  notify_auth_fail: boolean;
  notify_proxy_toggle: boolean;
  notify_proxy_port_conflict: boolean;
  notify_trigger_fail: boolean;
  notify_trigger_success: boolean;
  notify_ip_change: boolean;
  /// User-defined custom variables for trigger templates
  custom_variables: CustomVariable[];
}

/// User-defined custom variable for trigger templates
export interface CustomVariable {
  name: string;
  value: string;
}

/// Top-level config (matches Rust Config)
export interface Config {
  version: number;
  general: GeneralConfig;
  trigger_templates: TriggerTemplate[];
  servers: ServerConfig[];
}

// === IPC types ===

export interface IpcError {
  code: string;
  detail: string;
}

// === Log types ===

export interface LogEntry {
  id: string;
  timestamp: string;
  server_id: string | null;
  level: "info" | "warn" | "error";
  category: "Connection" | "Trigger" | "Proxy" | "Error" | "Config" | "System";
  message: string;
  execution_id: string | null;
  command: string | null;
  exit_code: number | null;
  stdout: string | null;
  stderr: string | null;
}

// === SECTION 2 END ===
