[target.aarch64-linux-android]
linker = "/Users/terry/Library/Android/sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "/Users/terry/Library/Android/sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7-linux-androideabi21-clang"

[target.x86_64-linux-android]
linker = "/Users/terry/Library/Android/sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang"
